from __future__ import annotations

import enum
from typing import Optional


class ErrorCategory(enum.Enum):
    AUTH = "auth"
    AUTHORIZATION = "authorization"
    AUTHENTICATION = "authentication"
    VALIDATION = "validation"
    NOT_FOUND = "not_found"
    CONFLICT = "conflict"
    DATABASE = "database"
    SERVICE = "service"
    EXTERNAL_SERVICE = "external_service"
    CONFIGURATION = "configuration"
    BUSINESS_RULE = "business_rule"
    INTEGRATION = "integration"
    STATE_MACHINE = "state_machine"
    AMORTIZATION = "amortization"
    APPROVAL = "approval"
    EXPENSE = "expense"
    FX = "fx"
    NOTIFICATION = "notification"
    SETTLEMENT = "settlement"
    CARRY_FORWARD = "carry_forward"
    DEBT = "debt"
    MIGRATION = "migration"
    OCR = "ocr"
    WATERMARK = "watermark"
    AUDIT = "audit"
    IDENTITY = "identity"
    LOGGING = "logging"
    UNKNOWN = "unknown"


class ErrorCode(str, enum.Enum):
    UNKNOWN = "UNKNOWN"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_MFA_REQUIRED = "AUTH_MFA_REQUIRED"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"
    AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED"
    AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED"

    FORBIDDEN = "FORBIDDEN"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    POLICY_VIOLATION = "POLICY_VIOLATION"

    VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD"
    VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT"
    VALIDATION_OUT_OF_RANGE = "VALIDATION_OUT_OF_RANGE"
    VALIDATION_INVALID_TYPE = "VALIDATION_INVALID_TYPE"
    VALIDATION_CONSTRAINT_VIOLATION = "VALIDATION_CONSTRAINT_VIOLATION"
    VALIDATION_UNEXPECTED_VALUE = "VALIDATION_UNEXPECTED_VALUE"

    NOT_FOUND = "NOT_FOUND"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    RELATIONSHIP_NOT_FOUND = "RELATIONSHIP_NOT_FOUND"

    CONFLICT_DUPLICATE = "CONFLICT_DUPLICATE"
    CONFLICT_VERSION = "CONFLICT_VERSION"
    CONFLICT_STATE = "CONFLICT_STATE"
    CONFLICT_LOCK = "CONFLICT_LOCK"

    DB_CONNECTION = "DB_CONNECTION"
    DB_QUERY = "DB_QUERY"
    DB_TIMEOUT = "DB_TIMEOUT"
    DB_INTEGRITY = "DB_INTEGRITY"
    DB_MIGRATION = "DB_MIGRATION"
    DB_CONSTRAINT = "DB_CONSTRAINT"

    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    SERVICE_TIMEOUT = "SERVICE_TIMEOUT"
    SERVICE_RATE_LIMIT = "SERVICE_RATE_LIMIT"
    SERVICE_DEPENDENCY_FAILURE = "SERVICE_DEPENDENCY_FAILURE"

    EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"
    EXTERNAL_TIMEOUT = "EXTERNAL_TIMEOUT"
    EXTERNAL_RATE_LIMIT = "EXTERNAL_RATE_LIMIT"
    EXTERNAL_AUTH_FAILED = "EXTERNAL_AUTH_FAILED"
    EXTERNAL_BAD_RESPONSE = "EXTERNAL_BAD_RESPONSE"

    CONFIG_MISSING = "CONFIG_MISSING"
    CONFIG_INVALID = "CONFIG_INVALID"
    CONFIG_TYPE_ERROR = "CONFIG_TYPE_ERROR"

    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
    BUSINESS_RULE_LIMIT_EXCEEDED = "BUSINESS_RULE_LIMIT_EXCEEDED"
    BUSINESS_RULE_PERIOD_CLOSED = "BUSINESS_RULE_PERIOD_CLOSED"

    INTEGRATION_MISMATCH = "INTEGRATION_MISMATCH"
    INTEGRATION_VERSION_CONFLICT = "INTEGRATION_VERSION_CONFLICT"
    INTEGRATION_CONTRACT_VIOLATION = "INTEGRATION_CONTRACT_VIOLATION"

    STATE_MACHINE_INVALID_TRANSITION = "STATE_MACHINE_INVALID_TRANSITION"
    STATE_MACHINE_INVALID_STATE = "STATE_MACHINE_INVALID_STATE"
    STATE_MACHINE_GUARD_FAILED = "STATE_MACHINE_GUARD_FAILED"

    AMORT_SCHEDULE_NOT_FOUND = "AMORT_SCHEDULE_NOT_FOUND"
    AMORT_CALCULATION_ERROR = "AMORT_CALCULATION_ERROR"
    AMORT_INVALID_PARAMS = "AMORT_INVALID_PARAMS"
    AMORT_PERIOD_MISMATCH = "AMORT_PERIOD_MISMATCH"

    APPROVAL_CHAIN_BROKEN = "APPROVAL_CHAIN_BROKEN"
    APPROVAL_ALREADY_DECIDED = "APPROVAL_ALREADY_DECIDED"
    APPROVAL_INSUFFICIENT = "APPROVAL_INSUFFICIENT"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"

    EXPENSE_DUPLICATE = "EXPENSE_DUPLICATE"
    EXPENSE_REJECTED = "EXPENSE_REJECTED"
    EXPENSE_POLICY_VIOLATION = "EXPENSE_POLICY_VIOLATION"
    EXPENSE_RECEIPT_MISSING = "EXPENSE_RECEIPT_MISSING"

    FX_RATE_NOT_FOUND = "FX_RATE_NOT_FOUND"
    FX_CONVERSION_ERROR = "FX_CONVERSION_ERROR"
    FX_RATE_EXPIRED = "FX_RATE_EXPIRED"

    NOTIF_DELIVERY_FAILED = "NOTIF_DELIVERY_FAILED"
    NOTIF_TEMPLATE_NOT_FOUND = "NOTIF_TEMPLATE_NOT_FOUND"
    NOTIF_CHANNEL_UNAVAILABLE = "NOTIF_CHANNEL_UNAVAILABLE"

    SETTLEMENT_RECONCILIATION_FAILED = "SETTLEMENT_RECONCILIATION_FAILED"
    SETTLEMENT_IMBALANCE = "SETTLEMENT_IMBALANCE"
    SETTLEMENT_ALREADY_SETTLED = "SETTLEMENT_ALREADY_SETTLED"

    CARRY_FORWARD_PERIOD_OPEN = "CARRY_FORWARD_PERIOD_OPEN"
    CARRY_FORWARD_PERIOD_MISMATCH = "CARRY_FORWARD_PERIOD_MISMATCH"
    CARRY_FORWARD_CALCULATION_ERROR = "CARRY_FORWARD_CALCULATION_ERROR"

    DEBT_ALREADY_SETTLED = "DEBT_ALREADY_SETTLED"
    DEBT_INSUFFICIENT_FUNDS = "DEBT_INSUFFICIENT_FUNDS"
    DEBT_VALIDATION_FAILED = "DEBT_VALIDATION_FAILED"

    MIGRATION_VERSION_CONFLICT = "MIGRATION_VERSION_CONFLICT"
    MIGRATION_ALREADY_APPLIED = "MIGRATION_ALREADY_APPLIED"
    MIGRATION_FAILED = "MIGRATION_FAILED"

    OCR_PROCESSING_FAILED = "OCR_PROCESSING_FAILED"
    OCR_UNREADABLE = "OCR_UNREADABLE"
    OCR_UNSUPPORTED_FORMAT = "OCR_UNSUPPORTED_FORMAT"
    OCR_TEXT_EXTRACTION_FAILED = "OCR_TEXT_EXTRACTION_FAILED"

    WATERMARK_VALIDATION_FAILED = "WATERMARK_VALIDATION_FAILED"
    WATERMARK_INTEGRITY_ERROR = "WATERMARK_INTEGRITY_ERROR"
    WATERMARK_NOT_FOUND = "WATERMARK_NOT_FOUND"

    AUDIT_TRAIL_BROKEN = "AUDIT_TRAIL_BROKEN"
    AUDIT_LOG_FAILED = "AUDIT_LOG_FAILED"
    AUDIT_INCONSISTENCY = "AUDIT_INCONSISTENCY"

    IDENTITY_VERIFICATION_FAILED = "IDENTITY_VERIFICATION_FAILED"
    IDENTITY_DOCUMENT_INVALID = "IDENTITY_DOCUMENT_INVALID"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"

    LOGGING_CONFIG_ERROR = "LOGGING_CONFIG_ERROR"
    LOGGING_SINK_FAILURE = "LOGGING_SINK_FAILURE"


def error_code_for_category(category: ErrorCategory, suffix: str = "ERROR") -> str:
    prefix = category.value.upper().replace("_", "")
    return f"{prefix}_{suffix}"
